#!/bin/bash

echo "removing stopped containers"
docker rm $(docker ps -a -q)

echo "removing dangling volumes"
docker volume rm $(docker volume ls -q --filter dangling=true)

echo "removing unused images"
docker rmi $(docker images --filter dangling=true -q)
