---

- name: fresh install
  hosts: all
  roles:
    - { role: backups, tags: ['backups'] }
    - { role: packages, tags: ['packages'] }
    - { role: security, tags: ['security'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: docker, tags: ['docker'] }
    - { role: environment, tags: ['tools'] }
  tags:
    - install
