---

- name: update all installed packages
  apt: update_cache=yes upgrade=safe

- name: install common packages
  apt: 
    update_cache=yes
    state=present
    install_recommends=no
    name={{item}}
  with_items: "{{ common_packages }}"
