---

- name: install common packages
  apt: 
    update_cache=yes
    state=present
    install_recommends=no
    name={{item}}
  with_items: "{{ common_packages }}"

- name: cronjob to run updates
  copy: src=updates.cron dest=/etc/cron.hourly/autoupdate mode="o=rwx,g=rx,o=rx" owner=root group=root 

- name: logrotate for update cron
  copy: src=updates.logrotate dest=/etc/logrotate.d/autoupdate mode="o=rw,g=r,o=r" owner=root group=root
