#!/bin/bash
# remove all unused docker containers, images and volumes
docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2> /dev/null
docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2> /dev/null
docker volume rm $(docker volume ls --filter dangling=true -q 2>/dev/null) 2> /dev/null
exit 0
